import { customAlphabet } from "nanoid";

const alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const newId = customAlphabet(alphabet, 16);
export const newToken = customAlphabet(alphabet, 32);

/** IDs accepted from clients (e.g. user message ids generated by useChat). */
export const CLIENT_ID_RE = /^[A-Za-z0-9_-]{8,64}$/;
