import { expect, test, type Page } from "@playwright/test";
import { Pool } from "pg";
import { mkdir } from "node:fs/promises";

test.skip(process.env.HERMES_PROVISIONING_BROWSER !== "1", "Requires disposable database and synthetic Hermes fixture");
const password = "Synthetic-hermes-fixture!42";
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const state = async () => (await fetch("http://127.0.0.1:19100/__test")).json();
async function login(page: Page, username: string) {
  await page.goto("/login");
  await page.getByLabel("Local username or email").fill(username);
  await page.getByLabel("Local password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in with local account" }).click();
  await page.waitForURL("/");
}
test.beforeAll(async () => {
  if (!process.env.DATABASE_URL?.endsWith("/collective_profiles_test")) throw new Error("Named disposable database required");
  const { createLocalUser } = await import("../../src/lib/auth/local");
  const { pool: appPool } = await import("../../src/db");
  await pool.query("DELETE FROM hermes_provisions WHERE user_id IN (SELECT id FROM users WHERE upn IN ('local:hermes-admin','local:hermes-member'))");
  await pool.query("DELETE FROM hermes_connections WHERE user_id IN (SELECT id FROM users WHERE upn IN ('local:hermes-admin','local:hermes-member'))");
  await pool.query("DELETE FROM users WHERE upn IN ('local:hermes-admin','local:hermes-member')");
  await pool.query("DELETE FROM ai_apps WHERE name='Browser managed bot · private Hermes profiles'");
  await pool.query("DELETE FROM local_auth_bootstrap");
  await pool.query("DELETE FROM auth_throttle");
  await fetch("http://127.0.0.1:19100/__test", { method: "POST", body: JSON.stringify({ reset: true, ready: true }) });
  process.env.LOCAL_AUTH_OPERATOR = "bootstrap";
  const admin = await createLocalUser({ username: "hermes-admin", name: "Hermes Fixture Admin", password, isAdmin: true }, "bootstrap");
  await createLocalUser({ username: "hermes-member", name: "Hermes Fixture Member", password }, { id: admin.id, sessionVersion: 0 });
  await pool.query("UPDATE local_credentials SET must_change_password=false,temporary_expires_at=null WHERE user_id IN (SELECT id FROM users WHERE upn IN ('local:hermes-admin','local:hermes-member'))");
  await appPool.end();
  await mkdir("/tmp/collective-hermes-screenshots", { recursive: true });
});
test.afterAll(async () => { await pool.end(); });

test("admin setup, ordinary-user denial, failed first use, retry, private routing and fresh sessions", async ({ page, browser }) => {
  await login(page, "hermes-admin");
  await page.goto("/admin/hermes");
  await expect(page.getByText("Hermes is single-tenant.", { exact: false })).toBeVisible();
  const [admin] = (await pool.query("SELECT id FROM users WHERE upn='local:hermes-admin'")).rows;
  await page.locator("select[name=userId]").selectOption(admin.id);
  await page.getByLabel("Operator isolation boundary ID").fill("browser-admin-boundary");
  await page.getByLabel("Dashboard loopback origin").fill("http://localhost:19100");
  await page.getByLabel("Runs loopback origin").fill("http://127.0.0.1:19101");
  await page.getByLabel("Exact Hermes version", { exact: true }).fill("mock-pinned");
  await page.getByLabel("Exact Hermes displayVersion").fill("mock-pinned");
  await page.getByLabel("Dashboard session token").fill("synthetic-dashboard-token");
  await page.getByLabel("Provider API key").fill("synthetic-provider-key");
  await page.getByLabel("Distinct profile API keys").fill("synthetic-admin-profile-key");
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Register runtime", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Check the isolation");
  await page.getByLabel("Dashboard loopback origin").fill("http://127.0.0.1:19100");
  const registration = page.waitForRequest((r) => r.method() === "POST" && new URL(r.url()).pathname === "/admin/hermes");
  await page.getByRole("button", { name: "Register runtime", exact: true }).click();
  const registrationRequest = await registration;
  const actionHeaders = await registrationRequest.allHeaders();
  await expect(page.getByRole("status")).toHaveText("Saved");
  await page.reload();
  await expect(page.getByLabel("Dashboard session token")).toHaveValue("");
  expect(await page.content()).not.toContain("synthetic-admin-profile-key");
  await page.getByLabel("Replacement dashboard token").fill("synthetic-rotated-dashboard-token");
  await page.getByRole("button", { name: "Replace dashboard token" }).click();
  await expect(page.getByLabel("Replacement dashboard token")).toHaveValue("");
  await page.getByLabel("Bot name", { exact: true }).fill("Browser managed bot");
  await page.getByLabel("Instructions", { exact: true }).fill("Only use synthetic fixture data.");
  await page.getByLabel("Native model ID").fill("mock-model");
  await page.getByRole("button", { name: "Create managed bot", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Saved");
  const context = await browser.newContext(); const member = await context.newPage();
  try {
    await login(member, "hermes-member");
    const denied = await member.request.post("/admin/hermes", { headers: { "next-action": actionHeaders["next-action"], "content-type": actionHeaders["content-type"], origin: process.env.BASE_URL! }, data: registrationRequest.postDataBuffer()! });
    expect(denied.status()).toBeGreaterThanOrEqual(400);
    await member.goto("/admin/hermes"); await expect(member).toHaveURL("/");
    await member.goto("/bots"); await member.getByRole("link", { name: "Chat with Browser managed bot", exact: true }).first().click();
    await member.getByLabel("Message", { exact: true }).fill("first use without a runtime");
    await member.getByLabel("Message", { exact: true }).press("Enter");
    await expect(member.getByText("Your Hermes runtime is not configured or has been disabled.", { exact: false })).toBeVisible();
    expect((await state()).profiles).toBe(0);

    await page.goto("/admin/hermes");
    const [u] = (await pool.query("SELECT id FROM users WHERE upn='local:hermes-member'")).rows;
    await page.locator("select[name=userId]").selectOption(u.id);
    await page.getByLabel("Operator isolation boundary ID").fill("browser-member-boundary");
    await page.getByLabel("Dashboard loopback origin").fill("http://127.0.0.1:19102");
    await page.getByLabel("Runs loopback origin").fill("http://127.0.0.1:19103");
    await page.getByLabel("Exact Hermes version", { exact: true }).fill("mock-pinned");
    await page.getByLabel("Exact Hermes displayVersion").fill("mock-pinned");
    await page.getByLabel("Dashboard session token").fill("synthetic-member-dashboard-token");
    await page.getByLabel("Provider API key").fill("synthetic-member-provider-key");
    await page.getByLabel("Distinct profile API keys").fill("synthetic-member-profile-key");
    await page.getByRole("checkbox").check();
    await page.getByRole("button", { name: "Register runtime", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Saved");
    await fetch("http://127.0.0.1:19100/__test", { method: "POST", body: JSON.stringify({ ready: false }) });
    await member.getByLabel("Message", { exact: true }).fill("try setup"); await member.getByLabel("Message", { exact: true }).press("Enter");
    await expect(member.getByText("Hermes profile setup is incomplete.", { exact: false })).toBeVisible();
    await expect(member.getByLabel("Message", { exact: true })).toHaveValue("try setup");
    await page.reload(); await expect(page.getByText("failed", { exact: false }).last()).toBeVisible();
    await page.screenshot({ path: "/tmp/collective-hermes-screenshots/admin-failure.png", fullPage: true });
    await fetch("http://127.0.0.1:19100/__test", { method: "POST", body: JSON.stringify({ ready: true }) });
    await pool.query("UPDATE hermes_provisions SET retry_after=now()-interval '1 minute' WHERE user_id=$1", [u.id]);
    await member.getByLabel("Message", { exact: true }).fill("retry setup"); await member.getByLabel("Message", { exact: true }).press("Enter");
    await expect(member.getByRole("main").getByText("Mock profile reply", { exact: true })).toBeVisible({ timeout: 45000 });
    // Regeneration fails before admission, but its prompt is already stored and must stay out of the composer.
    const conversationId = new URL(member.url()).pathname.split("/").at(-1)!;
    const storedBefore = (await pool.query("SELECT id FROM messages WHERE conversation_id=$1", [conversationId])).rows;
    await page.goto("/admin/hermes");
    const memberRuntime = page.locator("section > div").filter({ hasText: "browser-member-boundary" });
    await memberRuntime.getByRole("button", { name: "Disable runtime", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Saved");
    await member.getByRole("button", { name: "Regenerate", exact: true }).click();
    await expect(member.getByText("Your Hermes runtime is not configured or has been disabled.", { exact: false })).toBeVisible();
    await expect(member.getByRole("main").getByText("retry setup", { exact: true })).toBeVisible();
    await expect(member.getByLabel("Message", { exact: true })).toHaveValue("");
    expect((await pool.query("SELECT id FROM messages WHERE conversation_id=$1", [conversationId])).rows).toEqual(storedBefore);
    await member.screenshot({ path: "/tmp/collective-hermes-screenshots/regenerate-preserved.png", fullPage: true });
    await memberRuntime.getByRole("button", { name: "Enable runtime", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Saved");
    await member.reload();
    await expect(member.getByRole("main").getByText("Mock profile reply", { exact: true })).toBeVisible();
    const oldUrl = member.url(); const before = await state();
    await member.getByLabel("Message", { exact: true }).fill("/new"); await member.getByLabel("Message", { exact: true }).press("Enter");
    await expect(member).not.toHaveURL(oldUrl);
    await member.getByLabel("Message", { exact: true }).fill("new session"); await member.getByLabel("Message", { exact: true }).press("Enter");
    await expect(member.getByRole("main").getByText("Mock profile reply", { exact: true })).toBeVisible({ timeout: 45000 });
    const after = await state(); expect(after.profiles).toBe(before.profiles);
    expect(after.runs.at(-1).path).toBe(before.runs.at(-1).path);
    expect(after.runs.at(-1).body.session_id).not.toBe(before.runs.at(-1).body.session_id);
    await member.screenshot({ path: "/tmp/collective-hermes-screenshots/member-chat.png", fullPage: true });
    await page.goto("/bots"); await page.getByRole("link", { name: "Chat with Browser managed bot", exact: true }).first().click();
    await page.getByLabel("Message", { exact: true }).fill("admin uses same bot"); await page.getByLabel("Message", { exact: true }).press("Enter");
    await expect(page.getByRole("main").getByText("Mock profile reply", { exact: true })).toBeVisible({ timeout: 45000 });
    const both = await state(); expect(both.profiles).toBe(2); expect(both.runs.at(-1).origin).not.toBe(after.runs.at(-1).origin);
    const [definition] = (await pool.query("SELECT id FROM bots WHERE name='Browser managed bot'")).rows;
    await page.goto(`/bots/${definition.id}/edit`);
    await expect(page.getByPlaceholder("Name your bot", { exact: true })).toBeDisabled();
    await expect(page.locator("label").filter({ hasText: /^Instructions$/ }).locator("..").locator("textarea")).toBeDisabled();
    await expect(page.getByLabel("Model (app)", { exact: true })).toBeDisabled();
    await expect(page.getByText("Managed Hermes definitions preserve existing profiles", { exact: false })).toBeVisible();
    await page.goto("/admin/hermes"); await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: "/tmp/collective-hermes-screenshots/admin-mobile.png", fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  } finally { await context.close(); }
});
